actually fixing setup script

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,14 +1,22 @@
 #!/bin/sh
-if [ heroku join --app md-config-staging &> /dev/null ]; then
+# Exit if any subcommand fails
+set -e
+
+if heroku join --app md-config-staging &> /dev/null; then
   git remote add staging git@heroku.com:md-config-staging.git || true
-  printf 'You are a collaborator on the "md-config-staging" Heroku app\n'
+  printf 'You are a collaborator on the "md-config-staging" Heroku app
+'
 else
-  printf 'Ask for access to the "md-config-staging" Heroku app\n'
+  printf 'Ask for access to the "md-config-staging" Heroku app
+'
 fi
-if [ heroku join --app md-config-production &> /dev/null ]; then
+
+
+if heroku join --app md-config-production &> /dev/null; then
   git remote add production git@heroku.com:md-config-production.git || true
-  printf 'You are a collaborator on the "md-config-production" Heroku app\n'
+  printf 'You are a collaborator on the "md-config-production" Heroku app
+'
 else
-  printf 'Ask for access to the "md-config-production" Heroku app\n'
+  printf 'Ask for access to the "md-config-production" Heroku app
+'
 fi
-git config heroku.remote staging
